name: Test and Release 
on:
  push:
    branches: [ main ]

env:
  PYTHON_VERSION: "3.7"
  PROJECT_FOLDER: "mdatpy"
  TEST_FOLDER: tests
  
jobs:
  Quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{env.PYTHON_VERSION}}

    - name: Configure poetry & Install dependencies
      run: |
       python -m pip install --upgrade pip
       pip install poetry && poetry install
    
    - name: View poetry version
      run: poetry --version
    

    - name: Test with pytest
      run: |
        poetry run python -m pytest -v ${{env.TEST_FOLDER}}
    
  Release:
    needs: Quality
    # https://github.community/t/how-do-i-specify-job-dependency-running-in-another-workflow/16482
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Python Semantic Release
        uses: aadhithya/py-semantic-release-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          repository_username: ${{ secrets.PYPI_USER }}
          repository_password: ${{ secrets.PYPI_SECRET }}